### ISSUE TITLE
Promises returned from effects resolve to undefined

### ISSUE THREAD

**Issue by pierissimo** [rematch/rematch#208]
Calling an effect return correctly a promise, but the value that will be resolved is always undefined.
Link to codesandbox:

https://codesandbox.io/s/3x3l27jk8p

**Comment by ShMcK** [comment]
Which value are you expecting from the dispatch?

**Comment by pierissimo** [comment]
the value returned from the effect. In the example provided, the string 'hey there'.

**Comment by blairbodnar** [comment]
Ah, like this right?

```js
// 'count' model
effects: {
    async asyncIncrement() {
      await new Promise(resolve => {
        setTimeout(resolve, 1000);
      });
      dispatch.count.increment();
      return "hey there";
    }
  }
```

```js
// somewhere else
const handleAsyncIncrement = async () => {
    const value = await coiunt.dispatch.asyncIncrement();
    // expects value to be "hey there"    
  };
```

**Comment by ShMcK** [comment]
Interesting idea. That could probably be added. Out of curiousity, could you give an example of a use case?

Initially I added promises to help ensuring dispatches happen in the correct order. For example, validate a form THEN route to a different page.

The thing about dispatches in Redux is that they don't return any value. You send a message out into the ether, and if it has a listener, something happens - otherwise nothing.

**Comment by pierissimo** [comment]
Yes, the fact that they return a promise out of the box (without the necessity to add a custom middleware) is powerful.
But returning a promise that resolve to undefined, instead of a value could be misleading.
A use case could be the ability to fetch a value from the API, without saving it in the state (bypassing reducers/selectors).
I know that can be a bad approach, but there are situations where it can be useful.

The approach is used in vuex, where dispatched actions return promises that resolve to value.

**Comment by ShMcK** [comment]
The idea of a "model" is to put all your related code in one place. 

Even if the code doesn't need to interact with Redux, I think that makes a lot of sense.

**Comment by ShMcK** [comment]
The code that handles the returning promise is here: https://github.com/rematch/rematch/blob/master/src/plugins/effects.ts#L31-L37

Since it relies on Redux middleware, I'm not sure that it can return a value. But there's always a way.

**Comment by pierissimo** [comment]
It's definitely possible with redux middlewares, as I'm using a custom middleware to return values after dispatching submit with redux-forms.

I'm not sure, but maybe the createDispatcher function should return a value:
https://github.com/rematch/rematch/blob/master/src/plugins/dispatch.ts#L17

**Comment by pierissimo** [comment]
That line could be changed to:
```javascript
return storeDispatch(action)
```

**Comment by ShMcK** [comment]
Just tried the recommendation above. Unfortunately, it causes an infinite loop of dispatches.

Feel free to put in a PR if you have the time. There's enough test coverage that there's not much risk you can break anything.

And if you have any questions we're happy to help :)

**Comment by pierissimo** [comment]
@ShMcK I'll do, thank you very much!

**Comment by pierissimo** [comment]
https://github.com/rematch/rematch/pull/210
I implemented the change discussed, however the tests keep passing.
How can I reproduce the infinite loop of dispatches?
Thanks

**Comment by ShMcK** [comment]
I had added the dispatch within the middleware. My mistake!

**Comment by pierissimo** [comment]
If I remember correctly there was the loading plugin that interferes with the result of the effect.
If you are using it, try to disable it.

**Comment by mariusespejo** [comment]
Here's a fork of the sandbox app you had, updated to v0.6.0 of core, clicking the async button still alerts with an undefined resolved value:

https://codesandbox.io/s/382pm6r7wq

Your example there doesn't even use plugins.

**Comment by alphapseudo** [comment]
> Here's a fork of the sandbox app you had, updated to v0.6.0 of core, clicking the async button still alerts with an undefined resolved value:
https://codesandbox.io/s/382pm6r7wq

I can confirm that the issue is still present using `0.6.0` in my current implementation. I have yet to try the `1.0` alphas to see if it is resolved there.

**Comment by eeynard** [comment]
Hey, the issue isn't present in the latest build (1.0.0-alpha.4). But as @pierissimo said before, the loading plugin interferes with the result of the effect. I just pushed #371 to fix this issue, hope it'll help !

**Comment by scientist1642** [comment]
I updated to latest version but calling dispatch directly still returns undefined for me.
https://codesandbox.io/s/50yvpqjo3n
if you replace  `const value = await dispatch.count.asyncIncrement()` with `asyncIncrement()` it works fine.

**Comment by ShMcK** [comment]
@scientist1642 definitely your example shows something is not working. I'll look into this weekend, and increase the test coverage for this case.

**Comment by ShMcK** [comment]
In the example above using v1.0.0-alpha.4:

##### Global dispatch (no promise returned)

```js
const App = ({ count, increment }) => {
  const handleAsyncIncrement = async () => {
    const value = await dispatch.count.asyncIncrement(); // hey there
    alert(`resolved value: ${value}`);
  };
}
```

In order to support multiple stores, I'm not sure it's possible to return a promise from a global dispatch. There may be multiple promises resolving.

##### Local dispatch (promise returned)

```js
const App = ({ count, asyncIncrement, increment }) => {
  const handleAsyncIncrement = async () => {
    const value = await asyncIncrement(); // hey there
    alert(`resolved value: ${value}`);
  };
}
```

Local dispatch is bound to a specific store. This is why it is able to resolve the promise.

Using local dispatch is highly recommended.

**Comment by alozytskyi** [comment]
```
> git bisect bad
34639f221ba4f416b889018a1e8e9c58e3d47ff5 is the first bad commit
commit 34639f221ba4f416b889018a1e8e9c58e3d47ff5
Author: shmck <shawn.j.mckay@gmail.com>
Date:   Tue Mar 27 20:18:13 2018 -0700

    process action in effects

:040000 040000 8d52c96a3814a5f8fc12fe8f0650331ddb050c8e acc83ea05548bfe5c999621d47f23482b8f64676 M      src
```

**Comment by alozytskyi** [comment]
@ShMcK seems to be also working with latest v1.0.0

**Comment by baldrs** [comment]
This is working with rematch 0.5.4.

**Comment by d3dc** [comment]
@fkrauthan @baldrs @johnston

This is working in the `next` release.

I added a console log to this example: https://codesandbox.io/s/j32j4815k9

I wouldn't start a new project with a pre-1.0 version. In my opinion, everything that has changed is for the better and very little can break, as redux itself is not in beta.

As @ShMcK commented above, the only reason anything before 1.0 shouldn't do this is, is a technical reason. Does your application need more than one store? Just add a plain object for them in your own code.

**Comment by baldrs** [comment]
@d3dc do I need to do something specific to upgrade from 0.5.4 to 1.0.0-beta5 except upgrading package.json?

**Comment by fatehMohamed14** [comment]
Check this with latest rematch it returns a value https://codesandbox.io/s/rematch-example-react-count-forked-zolj4i
`"dependencies": {
    "@rematch/core": "2.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "8.0.5",
    "react-scripts": "^1.1.0",
    "redux": "4.2.1"
  },`
